// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestAPI.Data;

#nullable disable

namespace TestAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestAPI.Models.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnOrder(0);

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Key")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = 1,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Key = 1,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Key = 1,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Key = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 5,
                            Key = 2,
                            Value = 1
                        },
                        new
                        {
                            Id = 6,
                            Key = 2,
                            Value = 3
                        },
                        new
                        {
                            Id = 7,
                            Key = 2,
                            Value = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
